file=C:\\Users\\Martin Chalot\\Desktop\\Pernod Ricard\\Rollout\\RWB EE.xlsx

folder=C:\\Users\\Martin Chalot\\Desktop\\Pernod Ricard\\Rollout\\

full_debug=false



#Sheet name below will be analyzed as case insensitive
#Sheet not mentionned will be considered as object sheets
#Sheet APEX, TAB_VISIBILITY, etc. will be added to the sheet to ignore for object sheets
SHEET_APEX=Apex Components
SHEET_TAB_VISIBILITY=Tab Visibility
SHEET_LAYOUT_ASSIGNMENT=Page Layout assignment
SHEET_RECORD_TYPE_ASSIGNMENT=Record Type Assignment
SHEET_LISTVIEW=List Views
SHEET_SHARING_RULES=Sharing Rules

SHEETS_TO_IGNORE=List of actions,\
Offline objects,\
Standard Related List,\
Role Hierarchy,\
Revision History,Groups

PROFILES_TO_IGNORE=EUR System Admin,\
EUR EE On Trade User,\
EUR EE Off Trade User
#Hidden row will be automatically defined as false for field permissions
#unless you specify one or more profile splitted by a comma ","
PROFILES_DO_NOT_REMOVE_PERMISSIONS=EUR System Admin
